:encoding: utf-8
:lang: en
:title: Eclipse Extensions
:description: Extensions for the Eclipse IDE Java Development Tools
:keywords: eclipse, ide, java, jdt, cleanup, clean-up
:author: Christian Femers
:showtitle:
:numbered:
:icons: font

= Eclipse Extensions

A Personal Collection of Useful Extensions for the Eclipse IDE

This is a collection of various extensions to the Eclipse IDE,
mainly the Java Development Tools (JDT).
The update site URL is
https://extensions.eclipse.maisikoleni.net/repository/latest/
for the most recent build of all Eclipse feature plugins.

[WARNING]
====
As personal use is the main goal of my development efforts,
I cannot guarantee that it will work in all Eclipse versions.
The plugins often break the intended public API
barrier of the JDT modules, as without the internal API
I would need to reinvent the wheel a lot (or copy the code
into my project). I prefer to adjust to internal API changes
instead (should that ever be necessary).

The main aim is that the plugin works with the latest
Eclipse IDE release running on at least the latest LTS-JDK.
Currently, this is Eclipse 2022-03 with JDK 17+.
====

// ----------------------------------------------------------
// Display the following for standard GitHub AsciiDoc display
// ----------------------------------------------------------
ifdef::env-github[]

**Visit https://extensions.eclipse.maisikoleni.net/
for a more detailed documentation of all features.**

.Why is the documentation not availabe here?
[NOTE]
====
This README includes the individual AsciiDoc files
of all feature plugins and aggregates them into
one documentation, which is compiled and deployed
to GitHub Pages (using the aforementioned custom
domain).

The support for AsciiDoc inside GitHub itself
is good, but sadly lacks the intended functionality
of the include directive (it becomes a link instead).
See https://github.com/github/markup/issues/1095
for more information on that issue.
====

endif::env-github[]

// -------------------------------------------------------
// Otherwise, include the main content (e.g. GitHub Pages)
// -------------------------------------------------------
ifndef::env-github[]

== JDT Extensions

A feature plugin category that contains
Extensions for the Eclipse Java Development Tools
(https://www.eclipse.org/jdt/) of the Eclipse Java IDE.

include::features/net.maisikoleni.eclipse.extensions.jdt.cleanup.feature/README.adoc[leveloffset=1]

endif::env-github[]