# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
    - name: Checkout git repository
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Test and package with Maven
      uses: GabrielBB/xvfb-action@v1
      with:
        run: mvn -B verify
    - name: Upload failure logs if necessary
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: failure-logs-${{ github.sha }}
        path: tests/**/.log
        retention-days: 3
    - name: Upload updatesite artifact
      uses: actions/upload-artifact@v3
      with:
        name: updatesite-${{ github.sha }}
        path: releng/net.maisikoleni.eclipse.extensions.updatesite/target/repository/
        retention-days: 7
